# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'maoGang' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for maoGang

pod 'Masonry', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.1'
pod 'SDWebImage', '~> 4.4.1'
pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKUI'
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
pod 'SVProgressHUD', '~> 2.2.5'	
pod 'MBProgressHUD', '~> 1.1.0'
pod 'UIColor+SKYExtension', '0.0.1'
pod 'TTTAttributedLabel', '~> 2.0.0'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'UMCCommon'
pod 'UMCPush'
pod 'UMCSecurityPlugins'  
pod 'YYText', '~> 1.0.7'
target 'maoGangTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'maoGangUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
